application: odenkiapi
version: python-0006
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /post
  script: post.py

- url: /Sender
  script: SenderRequestHandler.py
  
- url: /RawData
  script: RawDataRequestHandler.py
  
- url: /Metadata
  script: MetadataRequestHandler.py
  
- url: /Data
  script: DataRequestHandler.py

- url: /Last
  script: LastRequestHandler.py

- url: /sandbox/hello
  script: sandbox/hello.py

- url: /Equipment
  script: Equipment.py
  
- url: /google686f6b490a533df7.html
  script: google686f6b490a533df7.py 

- url: /OdenkiUser
  script: OdenkiUser.py
  
- url: /Twitter
  script: Twitter.py
  
- url: /Facebook
  script: Facebook.py
  
- url: /Foursquare
  script: Foursquare.py

- url: /Spreadsheet
  script: Spreadsheet.py

- url: /Command
  script: Command.py
  
- url: /GoogleAuth*
  script: GoogleAuth.py
  
- url: /MyRequestHandler*
  script: MyRequestHandler.py
  
- url: /
  script: index.py
