application: odenkiapi
version: python-0005-nhk
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /html
  static_dir: html

- url: /css
  static_dir: css

- url: /api/([A-Za-z]+)
  script: api/\1.py

- url: /post
  script: post.py

- url: /
  script: index.py

- url: /Sender
  script: SenderRequestHandler.py
  
- url: /RawData
  script: RawDataRequestHandler.py
  
- url: /Metadata
  script: MetadataRequestHandler.py
  
- url: /Data
  script: DataRequestHandler.py

- url: /Last
  script: LastRequestHandler.py

- url: /sandbox/hello
  script: sandbox/hello.py

- url: /Equipment
  script: Equipment.py
  
- url: /GoogleDocs
  script: GoogleDocs.py

- url: /google686f6b490a533df7.html
  script: google686f6b490a533df7.py 

- url: /OdenkiUser
  script: OdenkiUser.py

- url: /Spreadsheet
  script: Spreadsheet.py

- url: /Command
  script: Command.py
  
